### ISSUE TITLE
Source

### ISSUE THREAD

**Issue by hoshsadiq** [Rampaigh/AutoIPTV#1]
Hi, like what you've done. Where is are the links coming from? And how can we contribute to improving the system?

**Comment by Rampaigh** [comment]
Hey, I've just added the contribute page: http://autoiptv.net/pages/contribute

**Comment by hoshsadiq** [comment]
Anyway we can contribute to playlist.php?

**Comment by Rampaigh** [comment]
Yes, whatever you add into: http://autoiptv.net/pages/contribute would add it automatically to all the playlists, including playlist.php...

Code wise, I wanna keep it hidden...

**Comment by hoshsadiq** [comment]
Ah okay. I meant code wise, but if you wanna keep it hidden, then no worries.
