### ISSUE TITLE
m3u8 url

### ISSUE THREAD

**Issue by churu88** [Rampaigh/AutoIPTV#4]
Hi Mate, all the url are .ts
I´d need the master.m3u8 url to see the content.
Could you provide it?

many thanks

**Comment by churu88** [comment]
Hi Rampaigh, you are right, I found some .m3u8. But just curious, looking at 24/7 playlist (attached below), how are we supposed to open those .ts? Another thing is that I can help you providing some m3u8 I have found on the web to add in this project. Cheers

x#EXTM3U

#EXTINF:0,*** AutoIPTV ***
https://autoiptv.net
#EXTINF:0,https://autoiptv.net
https://autoiptv.net
#EXTINF:0,*** Playlists ***
https://autoiptv.net/pages/playlists
#EXTINF:0,https://autoiptv.net/pages/playlists
https://autoiptv.net/pages/playlists
#EXTINF:0,SKY BUNDESLIGA 1 24/7 | HD
http://217.182.173.184:8000/live/asil/1234/312.ts
#EXTINF:0,SKY SPORT 1 24/7 | HD
http://217.182.173.184:8000/live/asil/1234/323.ts
#EXTINF:0,SKY SPORT 2 24/7 | HD
http://217.182.173.184:8000/live/asil/1234/322.ts
#EXTINF:0,24/7 | SD
http://iptv-area-51.tv:2095/live/pizza/1234/8539.ts
#EXTINF:0,24/7 | SD
http://iptv-area-51.tv:2095/live/pizza/1234/8531.ts
#EXTINF:0,24/7 | SD
http://iptv-area-51.tv:2095/live/pizza/1234/4607.ts
#EXTINF:0,24/7 | SD
http://iptv-area-51.tv:2095/live/pizza/1234/4837.ts
#EXTINF:0,24/7 | SD
http://iptv-area-51.tv:2095/live/pizza/1234/7374.ts
#EXTINF:0,24/7 | SD
http://iptv-area-51.tv:2095/live/pizza/1234/7375.ts
#EXTINF:0,24/7 | SD
http://iptv-area-51.tv:2095/live/pizza/1234/7377.ts
#EXTINF:0,24/7 | SD
http://iptv-area-51.tv:2095/live/pizza/1234/7379.ts
#EXTINF:0,24/7 | SD
http://iptv-area-51.tv:2095/live/pizza/1234/8109.ts
#EXTINF:0,24/7 | SD
http://iptv-area-51.tv:2095/live/pizza/1234/8130.ts
#EXTINF:0,24/7 | SD
http://iptv-area-51.tv:2095/live/pizza/1234/8134.ts
#EXTINF:0,24/7 | SD
http://iptv-area-51.tv:2095/live/pizza/1234/8152.ts
#EXTINF:0,24/7 | SD
http://iptv-area-51.tv:2095/live/pizza/1234/8153.ts
#EXTINF:0,24/7 | SD
http://iptv-area-51.tv:2095/live/pizza/1234/8529.ts
#EXTINF:0,24/7 | SD
http://iptv-area-51.tv:2095/live/pizza/1234/8530.ts
#EXTINF:0,24/7 | SD
http://iptv-area-51.tv:2095/live/pizza/1234/8535.ts
#EXTINF:0,24/7 | SD
http://iptv-area-51.tv:2095/live/pizza/1234/9208.ts
#EXTINF:0,24/7 | SD
http://iptv-area-51.tv:2095/live/pizza/1234/10941.ts
#EXTINF:0,24/7 | SD
http://iptv-area-51.tv:2095/live/pizza/1234/11460.ts
#EXTINF:0,24/7 | SD
http://iptv-area-51.tv:2095/live/pizza/1234/12033.ts
#EXTINF:0,24/7 | SD
http://iptv-area-51.tv:2095/live/pizza/1234/12248.ts
#EXTINF:0,24/7 | SD
http://iptv-area-51.tv:2095/live/pizza/1234/12250.ts
#EXTINF:0,24/7 | SD
http://reason4online.com:8080/live/Auntagency/csIrr6DjE3/8566.ts
#EXTINF:0,24/7 | SD
http://reason4online.com:8080/live/Auntagency/csIrr6DjE3/8567.ts
#EXTINF:0,24/7 | SD
http://reason4online.com:8080/live/Auntagency/csIrr6DjE3/8568.ts
#EXTINF:0,24/7 | SD
http://reason4online.com:8080/live/Auntagency/csIrr6DjE3/8569.ts
#EXTINF:0,24/7 | SD
http://reason4online.com:8080/live/Auntagency/csIrr6DjE3/8570.ts
#EXTINF:0,24/7 | SD
http://reason4online.com:8080/live/Auntagency/csIrr6DjE3/8571.ts
#EXTINF:0,24/7 | SD
http://reason4online.com:8080/live/Auntagency/csIrr6DjE3/8572.ts
#EXTINF:0,24/7 | SD
http://reason4online.com:8080/live/Auntagency/csIrr6DjE3/8573.ts
#EXTINF:0,24/7 | SD
http://reason4online.com:8080/live/Auntagency/csIrr6DjE3/8574.ts
#EXTINF:0,24/7 | SD
http://reason4online.com:8080/live/Auntagency/csIrr6DjE3/8575.ts
#EXTINF:0,24/7 | SD
http://reason4online.com:8080/live/Auntagency/csIrr6DjE3/8576.ts
#EXTINF:0,24/7 | SD
http://reason4online.com:8080/live/Auntagency/csIrr6DjE3/8577.ts
#EXTINF:0,24/7 FUTURAMA | SD
http://reason4online.com:8080/live/Auntagency/csIrr6DjE3/8578.ts
#EXTINF:0,RADIO | SD
http://iptv-area-51.tv:2095/live/pizza/1234/11129.ts

**Comment by Rampaigh** [comment]
So if you would like to contribute, you can head over to which would be much appreciated: https://autoiptv.net/pages/contribute/

As for trying to open the .ts links, correct me if this is not what you are asking? Must players that can open and read a .m3u or .m3u8 file should be able to play a .ts stream... 

Players that would make it easier to play can be found at: https://autoiptv.net/

Let me know if there is anything else?
